///////////////////////////////////////////////////////////
//  Comment.cs
//  Implementation of the Class Comment
//  Generated by Enterprise Architect
//  Created on:      06-Jun-2017 00:33:18
//  Original author: Alexis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
using BookingApp.Models;

namespace System {
	public class Comment {

        public int Id { get; set; }
		private int grade;
		private string text;
		public AppUser User;
		public Accommodation Accommodation;

		public Comment(){

		}

		~Comment(){

		}

		public int Grade{
			get{
				return grade;
			}
			set{
				grade = value;
			}
		}

		public string Text{
			get{
				return text;
			}
			set{
				text = value;
			}
		}

	}//end Comment

}//end namespace System