///////////////////////////////////////////////////////////
//  Comment.cs
//  Implementation of the Class Comment
//  Generated by Enterprise Architect
//  Created on:      06-Jun-2017 00:33:18
//  Original author: Alexis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace BookingApp.Models
{
    public class Comment
    {

        public int Id { get; set; }
        private int grade;
        private string text;

        /// <summary>
        /// Foreign key of accommodation
        /// </summary>
        [ForeignKey("User")]
        public int Refuser { get; set; }

        /// <summary>
        /// Foreign key of accommodation
        /// </summary>
        [ForeignKey("Accomodation")]
        public int RefAcc { get; set; }

        public Comment()
        {

        }

        public int Grade
        {
            get
            {
                return grade;
            }
            set
            {
                grade = value;
            }
        }

        public string Text
        {
            get
            {
                return text;
            }
            set
            {
                text = value;
            }
        }

    }//end Comment

}//end namespace System