///////////////////////////////////////////////////////////
//  Place.cs
//  Implementation of the Class Place
//  Generated by Enterprise Architect
//  Created on:      06-Jun-2017 00:33:18
//  Original author: Alexis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace BookingApp.Models
{
    public class Place
    {

        private int id;
        private string name;

        public List<Accommodation> m_Accommodation;

        /// <summary>
        /// Foreign key of region
        /// </summary>
        [ForeignKey("Region")]
        public int RefRegion { get; set; }


        public Place()
        {

        }


        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }

    }//end Place

}//end namespace System