///////////////////////////////////////////////////////////
//  RoomReservations.cs
//  Implementation of the Class RoomReservations
//  Generated by Enterprise Architect
//  Created on:      06-Jun-2017 00:33:18
//  Original author: Alexis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
using BookingApp.Models;

namespace System {
	public class RoomReservations {

        public int Id { get; set; }
		private DateTime? endDate;
		private DateTime? startDate;
		private DateTime? timestamp;
		public AppUser User;
		public Room Room;

		public RoomReservations(){

		}

		~RoomReservations(){

		}

		public DateTime? EndDate{
			get{
				return endDate;
			}
			set{
				endDate = value;
			}
		}

		public DateTime? StartDate{
			get{
				return startDate;
			}
			set{
				startDate = value;
			}
		}

		public DateTime? Timestamp{
			get{
                return timestamp;
			}
			set{
				timestamp = value;
			}
		}

	}//end RoomReservations

}//end namespace System