///////////////////////////////////////////////////////////
//  RoomReservations.cs
//  Implementation of the Class RoomReservations
//  Generated by Enterprise Architect
//  Created on:      06-Jun-2017 00:33:18
//  Original author: Alexis
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookingApp.Models
{
    public class RoomReservation
    {

        public int Id { get; set; }
        private DateTime? endDate;
        private DateTime? startDate;
        private DateTime? timestamp;

        [ForeignKey("AppUser")]
        public string AppUser_Id { get; set; }

        public AppUser AppUser { get; set; }

        [ForeignKey("Room")]
        public int Room_Id { get; set; }

        public Room Room { get; set; }

        public RoomReservation()
        {

        }


        public DateTime? EndDate
        {
            get
            {
                return endDate;
            }
            set
            {
                endDate = value;
            }
        }

        public DateTime? StartDate
        {
            get
            {
                return startDate;
            }
            set
            {
                startDate = value;
            }
        }

        public DateTime? Timestamp
        {
            get
            {
                return timestamp;
            }
            set
            {
                timestamp = value;
            }
        }

    }//end RoomReservations

}//end namespace System